services:
  a0-ts:
    image: tailscale/tailscale:latest
    container_name: a0-ts
    hostname: a0
    environment:
      - TS_AUTHKEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/a0-serve.json
    volumes:
      - ./ts-data/a0:/var/lib/tailscale
      - ./ts-config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: on-failure:10
    networks:
      - a0_net
    logging:
      options:
        max-size: "50m"

  agent-zero-server:
    image: frdel/agent-zero-run:latest
    container_name: agent-zero-server
    network_mode: service:a0-ts
    volumes:
      - ./agent_zero_data:/a0
    restart: on-failure:10
    depends_on:
      - a0-ts
    logging:
      options:
        max-size: "50m"  

networks:
  a0_net:
    driver: bridge

