services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-livesync-couchdb
#    user: 1000:1000
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
      - VIRTUAL_HOST=obsidian-livesync.reinhardt.ai
      - LETSENCRYPT_HOST=obsidian-livesync.reinhardt.ai
      - VIRTUAL_PORT=5984
    env_file:
      - .env
    volumes:
      - ${COUCHDB_DATA}:/opt/couchdb/data
      - ${COUCHDB_ETC}:/opt/couchdb/etc/local.d
    networks:
      - reinhardt_net
    logging:
      options:
        max-size: "50m"
    restart: on-failure:10


networks:
  reinhardt_net:
    external: true